apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-http-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-http
  template:
    metadata:
      labels:
        app: helloworld-http
    spec:
      containers:
      - name: helloworld-http-container
        image: helloworld-http-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80