apiVersion: v1
kind: Service
metadata:
  name: helloworld-http-service
spec:
  selector:
    app: helloworld-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080    # Specify a static port for NodePort
  type: NodePort        # Change the service type to NodePort